name: Deploy to Firebase Hosting on merge to preview
on:
  push:
    branches:
      - preview
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install the Firebase CLI
        run: |
          curl -sL https://firebase.tools | bash
      - name: Deploy to Firebase
        run: firebase hosting:channel:deploy learning-firebase-xylocone-preview --token "${{ secrets.FIREBASE_TOKEN }}"
